### ISSUE TITLE
Does pyre require watchman?

### ISSUE THREAD

**Issue by rpgoldman** [linnik/flycheck-pyre#1]
When I start up the pyre daemon per your instructions, I get a message about not having watchman configured.
Does flycheck-pyre require watchman? Or does it control calls to pyre so not need it?
Thanks

**Comment by linnik** [comment]
Hi!
`watchman` is required by `pyre` and should be configured on first `pyre init` command like so

```
(env) ~/w/example ❯❯❯ pyre init
 ƛ Also initialize a watchman configuration? [Y/n] y
{
    "version": "4.9.4",
    "watch": "/Users/test/workspace/example",
    "watcher": "fsevents"
}
 ƛ Which directory should pyre be initialized in? (Default: `.`):
 ƛ Successfully initialized pyre! You can view the configuration at `/Users/test/workspace/example/.pyre_configuration`.
(env) ~/w/example ❯❯❯
```

`flycheck-pyre` basically just calls `pyre check` command and does not have any external dependencies (aside from installed automatically with melpa)

**Comment by rpgoldman** [comment]
The reason I asked was that I had `pyre` *already* installed (without watchman) and was just running it by hand in batch mode (because I didn't have it integrated with emacs yet).
If you already have a copy of pyre and have been using it, then `pyre init` just prints that it found a previous `.pyre_configuration`, and exits.
But now I have pyre configured, watchman running, and I *think* all is well.  Thanks for the explanation.
